import SEO from '../components/SEO';import PageHero from '../components/PageHero';import {site} from '../data/site';
const pages={
 privacy:{title:'Privacy Policy',description:'Privacy policy for Pooja Gas Stove Services, including enquiry data, cookies, analytics, advertising and Google AdSense disclosures.',keywords:'Pooja Gas Stove Services privacy policy',sections:[
 ['Information We Collect','When you contact us, submit an enquiry or communicate by phone or email, we may receive information such as your name, phone number, email address, service location, appliance details and message. We use this information to respond to service requests, communicate about appointments and operate the website.'],
 ['Cookies, Analytics and Advertising','This website may use cookies or similar technologies for essential website functions, analytics and, after approval and configuration, advertising. Third-party vendors, including Google, may use cookies to serve ads based on a user’s prior visits to this or other websites. Google’s use of advertising cookies may enable Google and its partners to serve personalized or non-personalized ads, depending on consent, settings and applicable law.'],
 ['Google AdSense and Third-Party Vendors','If Google AdSense is enabled on this site, Google and other approved advertising vendors may place or read cookies, use web beacons, IP addresses or other identifiers for ad delivery, measurement, fraud prevention and related purposes. Users can manage personalized advertising through Google Ads Settings. Where required, we will use an appropriate consent mechanism before loading advertising or analytics technologies that require consent.'],
 ['EEA, UK and Switzerland Visitors','Before personalized Google advertising is enabled for visitors in the EEA, UK or Switzerland, the site owner should configure a Google-certified Consent Management Platform (CMP) that integrates with the IAB Transparency and Consent Framework where Google policy requires it.'],
 ['Data Sharing','We do not sell customer contact information. Information may be shared with service personnel or technology providers only where reasonably necessary to operate the website, respond to an enquiry, deliver requested service, comply with law or protect the website and users.'],
 ['Data Retention and Security','We retain enquiry information only for as long as reasonably needed for service, record-keeping or legal purposes. No internet transmission or storage method is completely secure, so absolute security cannot be guaranteed.'],
 ['Your Choices','You may contact us to ask about personal information you have provided or request correction or deletion where applicable. Cookie and advertising choices may also be available through your browser, consent interface and advertising provider settings.'],
 ['Contact','Privacy questions can be sent to '+site.email+'.']
 ]},
 cookies:{title:'Cookie Policy',description:'Cookie policy explaining how Pooja Gas Stove Services may use essential, analytics and advertising cookies, including Google advertising cookies.',keywords:'cookie policy, advertising cookies, AdSense cookies',sections:[
 ['What Cookies Are','Cookies are small data files that websites or service providers can store in a browser. They can support basic functionality, remember choices, measure usage and help deliver or measure advertising.'],
 ['Cookies This Site May Use','The site may use essential cookies required for site operation, analytics cookies if analytics is configured, and advertising cookies if Google AdSense or another advertising service is enabled. We do not enable optional advertising simply by publishing this policy; the related services must be configured separately.'],
 ['Google Advertising Cookies','If AdSense is enabled, Google and its partners may use cookies to serve and measure ads. Depending on user location, consent and account settings, ads may be personalized or non-personalized.'],
 ['Managing Cookies','You can manage cookies through your browser and, where provided, through the site’s consent interface. Blocking some cookies may affect website or advertising functionality.'],
 ['Policy Updates','We may update this Cookie Policy when website technologies or legal requirements change.']
 ]},
 terms:{title:'Terms of Use',description:'Terms governing use of the Pooja Gas Stove Services website, service information, enquiries, availability and intellectual property.',keywords:'terms of use Pooja Gas Stove Services',sections:[
 ['Website Use','This website provides information about Pooja Gas Stove Services and enables users to contact us about repair, maintenance, inspection and related kitchen appliance services. Use the website only for lawful purposes.'],
 ['Service Availability','Service descriptions are general. Availability depends on technician schedule, exact location, appliance type, condition, parts and whether the requested work falls within our supported scope. A website enquiry does not itself confirm an appointment.'],
 ['30-Minute Service References','Any reference to 30-minute service means that faster doorstep service may be available for applicable nearby locations, subject to technician availability and confirmation. It is not a guaranteed arrival time for every customer or locality.'],
 ['Pricing and Parts','Charges, parts, labour and visit requirements may vary by appliance and problem. Confirm applicable charges before authorizing work.'],
 ['Intellectual Property','Website text, branding, layout and original materials are owned by or licensed to Pooja Gas Stove Services unless otherwise stated. They may not be republished as another business’s content without permission.'],
 ['Changes','We may update these terms, website content or service information when reasonably necessary.']
 ]},
 disclaimer:{title:'Disclaimer',description:'Website and service disclaimer for Pooja Gas Stove Services covering general information, safety, third-party links and service outcomes.',keywords:'Pooja Gas Stove Services disclaimer',sections:[
 ['General Information','Website content is provided for general information about our services and common kitchen appliance maintenance topics. It is not a remote diagnosis of a specific gas, electrical or mechanical problem.'],
 ['Gas Safety','Gas leakage and LPG connection issues can be hazardous. Do not rely on website content when you believe there is an immediate danger. Stop using the affected appliance where safe to do so and contact the appropriate emergency service, gas provider or qualified professional.'],
 ['No Guaranteed Repair Outcome','Some appliances may not be economical or practical to repair, and parts availability can vary. An on-site inspection may be required before repair feasibility can be confirmed.'],
 ['Third-Party Services and Ads','The website may contain links, analytics or advertising supplied by third parties. Their content, availability and privacy practices are controlled by the relevant provider.'],
 ['Accuracy','We aim to keep business and service information accurate, but service coverage, availability and website details may change. Contact us to confirm current information before relying on it for a booking.']
 ]},
 editorial:{title:'Content & Editorial Policy',description:'Editorial standards for service pages and educational guides published by Pooja Gas Stove Services.',keywords:'editorial policy, content policy, appliance repair guides',sections:[
 ['Purpose of Our Content','Our website content is written to explain the services we offer, help customers understand common appliance symptoms and provide safety-conscious maintenance information.'],
 ['People-First Writing','We avoid publishing pages solely to repeat keywords or city names. Service pages are organized around real customer needs, and location references are used to explain genuine service coverage.'],
 ['Safety and Accuracy','We avoid presenting hazardous gas work as a DIY task. Where a topic involves possible leakage, regulators, connections or internal gas controls, readers are encouraged to stop unsafe use and seek appropriate professional help.'],
 ['Updates and Corrections','We may revise pages when services, coverage areas, policies or technical information changes. If you notice an error, contact us at '+site.email+'.'],
 ['Advertising Independence','If advertising is enabled, ad placement does not change our service descriptions or safety guidance. Advertisements are not endorsements unless explicitly stated.']
 ]}
};
export default function LegalPage({type}){const p=pages[type];const path=type==='privacy'?'/privacy-policy':type==='cookies'?'/cookie-policy':type==='terms'?'/terms-of-use':type==='disclaimer'?'/disclaimer':'/editorial-policy';return <><SEO title={`${p.title} | ${site.name}`} description={p.description} keywords={p.keywords} path={path}/><PageHero title={p.title} text={`Last updated: August 17, 2026`}/><section className="section"><article className="container legal-content">{p.sections.map(([h,b])=><section key={h}><h2>{h}</h2><p>{b}</p></section>)}{type==='privacy'&&<div className="policy-links"><h2>Advertising & Privacy Choices</h2><p>For more information about how Google uses data on partner sites, see <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noreferrer">Google’s partner-sites privacy information</a>. You can manage personalized advertising through <a href="https://adssettings.google.com/" target="_blank" rel="noreferrer">Google Ads Settings</a>.</p></div>}</article></section></>}
